### ISSUE TITLE
这个是数据库多用户版本么

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr#1]
分支，akkariiin/dev
修改哪里可以改成json多用户？

**Comment by ghost** [comment]
tcprelay.py:1097 hostname <www.google.com> is block by the black hostname list when handling connection from

**Comment by Akkariiin** [comment]
暂时无法提供多用户支持

另外上面这个错误现在已经修复了
这个错误属于一个新功能

**Comment by Justsoos** [comment]
SSR Return ~ :smirk:

**Comment by Akkariiin** [comment]
@Justsoos No, SSR are dead.

**Comment by Akkariiin** [comment]
这个新功能是black_hostname_list
详见 https://github.com/shadowsocksrr/shadowsocks-rss/wiki/config.json

**Comment by Justsoos** [comment]
破娃酱的说话风格是那么不容易伪装得啊，自己心血也不会那么忍心丢掉。还愉快的活着，就好 ~

**Comment by Akkariiin** [comment]
@Justsoos 我不是破娃，谢谢
