### ISSUE TITLE
Python3.9环境下auth_chain_d似乎会报错

### ISSUE THREAD

**Issue by jwchenzju** [shadowsocksrr/shadowsocksr#103]
在almalinux9和python3.9环境下能启动，但连接时日志显示：
shell.py:49 can not initialize cipher context
tcprelay.py:905 exception from ......
我试过chacha20没有问题，不知道是不是PYTHON更新后的问题，感谢大神。

**Comment by RabbitGTI** [comment]
似乎是新版linux的问题，server是好的，其他设备能上。在unbutntu 22.04 client试了python2.7和3.10都是报错:

shadowsocks/crypto/openssl.py", line 111, in __init__
    raise Exception('can not initialize cipher context')

**Comment by jwchenzju** [comment]
我改用了TEDDYSUN的DOCKER版，环境是python3.7.9就没这问题了。建议其它朋友也考虑DOCKER算了。
