### ISSUE TITLE
运行一段时间后报错

### ISSUE THREAD

**Issue by 64611187** [shadowsocksrr/shadowsocksr#12]
2017-10-05 08:07:13 ERROR    server_pool.py:87 'NoneType' object has no attribute 'dispose'
Traceback (most recent call last):
  File "/home/shadowsocksr/server_pool.py", line 81, in _loop
    loop.run()
  File "/home/shadowsocksr/shadowsocks/eventloop.py", line 221, in run
    handle = handler.handle_event(sock, fd, event) or handle
  File "/home/shadowsocksr/shadowsocks/tcprelay.py", line 1443, in handle_event
    handle = handler.handle_event(sock, fd, event)
  File "/home/shadowsocksr/shadowsocks/tcprelay.py", line 1062, in handle_event
    self._on_remote_read(sock == self._remote_sock)
  File "/home/shadowsocksr/shadowsocks/tcprelay.py", line 960, in _on_remote_read
    self.destroy()
  File "/home/shadowsocksr/shadowsocks/tcprelay.py", line 1166, in destroy
    self._encryptor.dispose()
AttributeError: 'NoneType' object has no attribute 'dispose'
2017-10-05 08:07:14 INFO     server_pool.py:184 stopped server at 0.0.0.0:30550 already stop
2017-10-05 08:07:14 INFO     server_pool.py:202 stopped server at [::]:30550
2017-10-05 08:07:14 INFO     server_pool.py:184 stopped server at 0.0.0.0:30551 already stop
2017-10-05 08:07:14 INFO     server_pool.py:202 stopped server at [::]:30551
IPv6 not support

**Comment by Akkariiin** [comment]
使用的哪个加密算法`methon`？什么系统？py2/py3？服务器代码的版本？

**Comment by 64611187** [comment]
系统：CentOS 7.4.1708 py2.7
管理面板： ssrpanel
加密方式：chacha20-ietf
协议：auth_chain_a
混淆：tls1.2_ticket_auth
代码版本：akkariiin/master 9月1日

**Comment by Akkariiin** [comment]
`chacha20-ietf` ? 不应该呀....

**Comment by KarlM11** [comment]
I've meet a same problem.

- Commit: 1c4680b
- System: Ubuntu 16.04 with 4.4.0-97-generic
- Python: 2.7.12
- Method: `aes-256-cfb`
- Protocol: `auth_chain_a`
- Obfs: `tls1.2_ticket_auth`

My VPS does not have any IPv6 address, and after several IPv6 requests (with bad IPv6 address), it crashed with same message as @64611187 

Logs below.
```
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:31247
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    shell.py:49 102
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:31243
Nov 08 03:56:16 ru-3 server.py[2318]: 2017-11-08 03:56:16 ERROR    shell.py:49 104
Nov 08 03:56:40 ru-3 server.py[2318]: 2017-11-08 03:56:39 INFO     tcprelay.py:1364 port 443 connections down to 25
Nov 08 03:56:56 ru-3 server.py[2318]: 2017-11-08 03:56:56 INFO     tcprelay.py:1361 port 443 connections up to 50
Nov 08 03:57:15 ru-3 server.py[2318]: 2017-11-08 03:57:15 INFO     tcprelay.py:1364 port 443 connections down to 25
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:22087
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    shell.py:49 26
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:37309
Nov 08 03:58:05 ru-3 server.py[2318]: 2017-11-08 03:58:05 ERROR    shell.py:49 26
Nov 08 03:58:45 ru-3 server.py[2318]: 2017-11-08 03:58:45 ERROR    tcprelay.py:1097 unable to parse hostname cdn.staticfile.org when handling connection from ::ffff:61.48.41.250:39613
Nov 08 03:58:55 ru-3 server.py[2318]: 2017-11-08 03:58:55 ERROR    tcprelay.py:1097 unable to parse hostname cdn.staticfile.org when handling connection from ::ffff:61.48.41.250:19038
Nov 08 03:59:15 ru-3 server.py[2318]: 2017-11-08 03:59:15 INFO     tcprelay.py:1361 port 443 connections up to 50
Nov 08 03:59:59 ru-3 server.py[2318]: 2017-11-08 03:59:59 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 03:59:59 ru-3 server.py[2318]: 2017-11-08 03:59:59 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:45892
Nov 08 03:59:59 ru-3 server.py[2318]: 2017-11-08 03:59:59 ERROR    shell.py:49 40
Nov 08 04:01:31 ru-3 server.py[2318]: 2017-11-08 04:01:31 INFO     tcprelay.py:1364 port 443 connections down to 25
Nov 08 04:01:54 ru-3 server.py[2318]: 2017-11-08 04:01:54 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:01:54 ru-3 server.py[2318]: 2017-11-08 04:01:54 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:44314
Nov 08 04:01:54 ru-3 server.py[2318]: 2017-11-08 04:01:54 ERROR    shell.py:49 15
Nov 08 04:08:34 ru-3 server.py[2318]: 2017-11-08 04:08:34 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:08:34 ru-3 server.py[2318]: 2017-11-08 04:08:34 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:17565
Nov 08 04:08:34 ru-3 server.py[2318]: 2017-11-08 04:08:34 ERROR    shell.py:49 49
Nov 08 04:12:50 ru-3 server.py[2318]: 2017-11-08 04:12:50 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:12:50 ru-3 server.py[2318]: 2017-11-08 04:12:50 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:17381
Nov 08 04:12:50 ru-3 server.py[2318]: 2017-11-08 04:12:50 ERROR    shell.py:49 17
Nov 08 04:13:01 ru-3 server.py[2318]: 2017-11-08 04:13:01 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:13:01 ru-3 server.py[2318]: 2017-11-08 04:13:01 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:17923
Nov 08 04:13:01 ru-3 server.py[2318]: 2017-11-08 04:13:01 ERROR    shell.py:49 20
Nov 08 04:13:33 ru-3 server.py[2318]: 2017-11-08 04:13:33 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:13:33 ru-3 server.py[2318]: 2017-11-08 04:13:33 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:19654
Nov 08 04:13:33 ru-3 server.py[2318]: 2017-11-08 04:13:33 ERROR    shell.py:49 19
Nov 08 04:20:00 ru-3 server.py[2318]: 2017-11-08 04:20:00 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:20:00 ru-3 server.py[2318]: 2017-11-08 04:20:00 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:40101
Nov 08 04:20:00 ru-3 server.py[2318]: 2017-11-08 04:20:00 ERROR    shell.py:49 19
Nov 08 04:21:07 ru-3 server.py[2318]: 2017-11-08 04:21:07 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:21:07 ru-3 server.py[2318]: 2017-11-08 04:21:07 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:42679
Nov 08 04:21:07 ru-3 server.py[2318]: 2017-11-08 04:21:07 ERROR    shell.py:49 23
Nov 08 04:24:51 ru-3 server.py[2318]: 2017-11-08 04:24:51 ERROR    shell.py:49 [Errno 101] Network is unreachable
Nov 08 04:24:51 ru-3 server.py[2318]: 2017-11-08 04:24:51 ERROR    tcprelay.py:812 exception from ::ffff:61.48.41.250:14802
Nov 08 04:24:51 ru-3 server.py[2318]: 2017-11-08 04:24:51 ERROR    shell.py:49 20
Nov 08 04:28:49 ru-3 server.py[2318]: 2017-11-08 04:28:49 ERROR    shell.py:49 'NoneType' object has no attribute 'dispose'
Nov 08 04:28:49 ru-3 server.py[2318]: IPv6 support
Nov 08 04:28:49 ru-3 systemd[1]: shadowsocksr@config.service: Main process exited, code=exited, status=1/FAILURE
Nov 08 04:28:49 ru-3 systemd[1]: shadowsocksr@config.service: Unit entered failed state.
Nov 08 04:28:49 ru-3 systemd[1]: shadowsocksr@config.service: Failed with result 'exit-code'.
```

**Comment by KarlM11** [comment]
Seems this has been fixed in commit ca740c8 .

**Comment by casparpoon** [comment]
I encountered the same occasionally.

Commit: a3cf025
System: Ubuntu 16.04
Python: 2.7.12
Method: none
Protocol: auth_chain_d
Obfs: tls1.2_ticket_auth

Process log as below:

2017-11-15 21:05:59 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-15 21:08:59 INFO     tcprelay.py:1361 port 10338 connections up to 75
2017-11-15 21:11:09 INFO     tcprelay.py:1364 port 10338 connections down to 50
2017-11-15 21:16:15 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-15 23:19:09 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-15 23:25:28 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-15 23:35:41 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-15 23:39:45 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-16 02:40:00 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-16 02:42:42 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-16 02:52:10 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-16 02:56:48 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-16 03:03:19 INFO     tcprelay.py:1361 port 10338 connections up to 50
2017-11-16 03:07:25 INFO     tcprelay.py:1364 port 10338 connections down to 25
2017-11-16 04:28:57 ERROR    shell.py:49 'NoneType' object has no attribute 'dispose'

**Comment by KarlM11** [comment]
@casparpoon Try update to the newest version.
Just go straight and `git pull` the branch named `akkariiin/dev`.

**Comment by casparpoon** [comment]
@AspirinGeyer Thanks AspirinGeyer. Will try later.

**Comment by casparpoon** [comment]
Has been running for 10+ days and the issue did not happen again. Thanks @Akkariiin and @AspirinGeyer .

**Comment by Tsahao** [comment]
Same issue.
Seems that don't affect visiting the websites, just too many errors.
