### ISSUE TITLE
不支持obfs:tls_simple

### ISSUE THREAD

**Issue by timwa0669** [shadowsocksrr/shadowsocksr#16]
如题，希望加一下这个功能。

**Comment by Akkariiin** [comment]
这个是什么功能？SS的obfs插件吗？对应的SSR混淆应该是tls1.2

**Comment by timwa0669** [comment]
如图
![img_20171015_071542](https://user-images.githubusercontent.com/24656878/31580105-fd4e240e-b178-11e7-8779-f20b94a01a2f.jpg)

**Comment by timwa0669** [comment]
顺便一提，ssrr的客户端好像不支持random_head的混淆方式。

**Comment by Akkariiin** [comment]
旧的协议和混淆都出于安全的考虑隐藏了，不建议使用它们。
