### ISSUE TITLE
新协议的说明缺少

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr#17]
新的 auth_chain_e和f的说明没有添加

**Comment by leukios** [comment]
我还有个问题。auth_chain_*系列协议的建议加密是none。但是可以指定一个加密吗？这样爬墙效果会不会更好？

**Comment by Akkariiin** [comment]
说明稍后会添加，同时会更新auth_chain_*系列的选择建议

auth_chain_*系列自带rc4-md5加密，如果你喜欢的话，我推荐chacha20，或者如果能够使用的话新的Xchacha20在任何时候都是比chacha20更好的选择。

**Comment by leukios** [comment]
libsodium只能自己下载源码包编译吗？可以用Debian apt库里的版本吗？

**Comment by heromeng** [comment]
@Akkariiin 期待你对协议的更新

**Comment by Akkariiin** [comment]
@qijiangh 只关心libsodium的版本，至于是自己编译的还是预编译的，都没什么区别
