### ISSUE TITLE
`ShadowsocksR` 同样受到 `Shadowsocks` 中安全漏洞的影响

### ISSUE THREAD

**Issue by KarlM11** [shadowsocksrr/shadowsocksr#19]
[X41 D-Sec GmbH Security Advisory: X41-2017-008](https://github.com/shadowsocks/shadowsocks/issues/995) 中提到的 **Bruteforcable shadowsocks traffic because of MD5** 在本项目中同样存在。

参见 `shadowsocks/encrypt.py +60~67` 。

**Comment by Akkariiin** [comment]
https://github.com/shadowsocks/shadowsocks/issues/995#issuecomment-336622124
https://github.com/shadowsocks/shadowsocks/issues/995#issuecomment-336699055

**Comment by Akkariiin** [comment]
从 argon2 算法的设计的角度来说，不关心密码存储安全的SS系列没有使用argon2的必要。

另外这个算法的更新会涉及到所有现存的混淆及协议，影响前向兼容性，所以即使要更新也只会是在新增加的算法或协议中换用argon2算法。
