### ISSUE TITLE
Is this normal for memory usage?

### ISSUE THREAD

**Issue by Balnea** [shadowsocksrr/shadowsocksr#20]
Hi,
Please see the attachment of capture.
My OS is Ubuntu 16.06
Python version 2.7.13
Server version 3.2.1(newest)
Method: none
Protocol: auth_chain_a
Obfs: tls1.2
The VPS is used by myself only, with Android, C# and Python clients (not at the same time) for almost two days.
I just wonder in a common sense how much memory would it cost for a single Youtube user?
P.S. I have referred to the article of optimizing the performance:
https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks
Also TCP_BBR is applied
<img width="946" alt="free" src="https://user-images.githubusercontent.com/11453121/31709582-01a9c96e-b425-11e7-88f2-8e9ba98c0cc9.PNG">
<img width="528" alt="top" src="https://user-images.githubusercontent.com/11453121/31709589-061d4a0c-b425-11e7-8a6d-9b99b1575aba.PNG">

**Comment by Akkariiin** [comment]
已确认存在此问题，正在排查。

现已确认此问题仅出现在 `auth_chain_a` 及其后续 `auth_chain_*` 协议 。
如确实受到此问题影响，请暂时使用auth-aesxxx-md5/sha1协议

**Comment by Akkariiin** [comment]
fixed by f61bbefa95ee43c485b44f0fc0e1a8af92e2a452

**Comment by Balnea** [comment]
Thank you.
Waiting for you to release the stable version.
Now we use crond to restart the service everyday.

**Comment by Akkariiin** [comment]
now, this fix was stable, you can use it first. : )
