### ISSUE TITLE
git clone最新版

### ISSUE THREAD

**Issue by JHrockice** [shadowsocksrr/shadowsocksr#22]
请问我用git clone https://github.com/shadowsocksrr/shadowsocksr.git，
然而安装的不是你改进的支持auth-chain-e和f的最新版，还是破娃最后一版支持auth-china-ab的那版。
我的命令应该如何改？

**Comment by chesterlyd** [comment]
现在哪个分支是最新的？
`git checkout 远程分支`

**Comment by Balnea** [comment]
git clone不是默认最新版本吗？

**Comment by JHrockice** [comment]
谢谢LYDfalse，搞定了。

**Comment by ic0n** [comment]
~~~ bash
git clone https://github.com/shadowsocksrr/shadowsocksr --branch akkariiin/master --depth 1
# --branch 制定分支
# --depth 1 节省流量（如果你只是clone下来用的话）
~~~

**Comment by JHrockice** [comment]
@ic0n Reinstall SSRR with your simple command successfully. Thanks.
