### ISSUE TITLE
访问强制HSTS的网站(如twitter.com)，提示“您的连接并不安全”

### ISSUE THREAD

**Issue by Declarcall** [shadowsocksrr/shadowsocksr#23]
使用auth_chain_d以后的协议，访问强制使用HSTS的网站都会有这类提示。请教下，如何解决

**Comment by AkaneAkaza** [comment]
和协议没有关系

**Comment by Akkariiin** [comment]
你的服务器网络环境可能不怎么安全，或者你的电脑开启了国产软件

**Comment by Declarcall** [comment]
那也许是"服务器网络环境可能不怎么安全",我的电脑并没有国产软件

**Comment by Akkariiin** [comment]
@Declarcall （笑）你可以换一个服务器试试

**Comment by Declarcall** [comment]
@Akkariiin 好的，谢谢"小姐姐"啦 ！
