### ISSUE TITLE
关于新的分支2to3

### ISSUE THREAD

**Issue by gegehennb** [shadowsocksrr/shadowsocksr#25]
好像是前几天刚添加的。请问大佬可以简单介绍下这个版本主要有什么不同吗？？谢谢大佬

**Comment by Balnea** [comment]
顾名思义嘛！
Python2=>Python3

**Comment by gegehennb** [comment]
好吧，好吧，谢谢楼上大佬，关闭问题

**Comment by KarlM11** [comment]
**不要使用此分支**
这个分支主要是检查并修正已经过时的方法，测试新版本的 Python 的兼容性，以及修正 PEP-8 问题。完成测试之后会合并至主分支。
