### ISSUE TITLE
ssr性能问题

### ISSUE THREAD

**Issue by leeecho** [shadowsocksrr/shadowsocksr#26]
我的服务端配置文件如下：
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "local_address": "0.0.0.0",
    "local_port": 1081,

    "password": "xxxxxx",
    "method": "aes-128-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "speed_limit_per_con": 100,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}

发现连接数多的时候，CPU使用率达到50%（4c vps），而内存使用非常少，请问如何提高性能？提高并发连接数。谢谢。

**Comment by AkaneAkaza** [comment]
这个目前无解

**Comment by Akkariiin** [comment]
大约多少连接？连接是无活动的还是频繁活动的？是否是BT连接？

**Comment by leeecho** [comment]
UDP数据包多一点，连接数通过系统查看如下：
[root@localhost ~]# ss -s
Total: 1526 (kernel 2026)
TCP:   403 (estab 1, closed 98, orphaned 0, synrecv 0, timewait 98/0), ports 0

Transport Total     IP        IPv6
*         2026      -         -        
RAW       0         0         0        
UDP       666       366       300      
TCP       305       5         300      
INET      971       371       600      
FRAG      0         0         0

**Comment by Akkariiin** [comment]
emmmm 
按理来说这么一点连接不应该消耗这么多cpu，不知道是不是event驱动的问题？
emmmm

**Comment by leeecho** [comment]
我换成shadowsocks-libev多三倍的连接数，CPU才到10%不到。不知道能不能解决这个问题，是python性能问题吗？

**Comment by leeecho** [comment]
![image](https://user-images.githubusercontent.com/3860877/33806520-66327a9e-de04-11e7-8945-119404c58ec2.png)

**Comment by leeecho** [comment]
我用的版本是ShadowsocksR 3.3.3 2017-06-03。为什么你这里没有这个版本呢？

**Comment by Akkariiin** [comment]
3.3.3是manyuser分支上的最后一个提交，也许你使用的不是SSRR，也有可能使用了一个假的SSR。
你可以尝试切换到SSRR的akkariiin/master分支上再试

另外，C实现本来就比PY实现的运行效率高得多，更何况SS没有SSR/R这么复杂的协议和混淆系统
