### ISSUE TITLE
client没有GUI的情况下如何进行配置和启动？

### ISSUE THREAD

**Issue by pengcheng789** [shadowsocksrr/shadowsocksr#30]
在`READNE.md`里client相关的介绍是windows或OpenWRT之类带有GUI的客户端，我使用的是Ubuntu17.10，请问下该如何使用这个客户端？谢谢哈！

**Comment by KarlM11** [comment]
运行 `shadowsocks/local.py` 即可。传参参考服务端。

**Comment by pengcheng789** [comment]
@AspirinGeyer 谢谢说明哈。在配置过程中，发现local.py好像没有`协议参数`（`protocol_param`）的配置（好像跟`混淆参数`不同），但我购买的shadowsocks账号上却有这个参数，能再说明下这个参数怎么配置吗？

**Comment by pengcheng789** [comment]
看一下源码，在加载配置文件时候，有载入`protocol_param`参数，只是没有提示，尴尬。。。
