### ISSUE TITLE
[Question] regarding encryption about chain series

### ISSUE THREAD

**Issue by Balnea** [shadowsocksrr/shadowsocksr#39]
Hi,
Akkariiin, thank you for your hard work.
I have a question about chain series. According to breakwa11, the data is already encrypted with RC4 method. However, if the setting of the server we use, for example, 'chacha20' instead of 'none', will the data be encrypted with the new method instead? or this option is totally ignored and the original method is still applied? or the data first will be encrypted with RC4 and then with chacha20? I am a little confused about this setting.

**Comment by AkaneAkaza** [comment]
encrypted with RC4 and then with chacha20

**Comment by Balnea** [comment]
thanks
