### ISSUE TITLE
用不了auth_chain_e and auth_chain_f

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr#40]
使用dev branch，已经pull到最新
auth_chain_a b c d 都是正常的 只有e f没办法用
tcprelay.py:521 Protocol ERROR, TCP ogn data
上面是在日志里出现的
client 和 server的时区以及时间几乎没有差别
不知道是哪里出现问题了emmm

**Comment by Akkariiin** [comment]
正在修
