### ISSUE TITLE
搭建成功，但在24小时内ip被封

### ISSUE THREAD

**Issue by Tanlet** [shadowsocksrr/shadowsocksr#42]
你好！我使用秋水逸冰的脚本安装你的ssr，但是，24小时内ip又被封杀！别问我为什么又是“又”。
1.脚本地址
https://teddysun.com/486.html
2.配置参数
{
    "server":"0.0.0.0",
    "server_ipv6":"::",
    "server_port":1984,
    "port_password":{},
    "local_address":"127.0.0.1",
    "local_port":1080,
    "timeout":120,
    "method":"none",
    "protocol":"auth_chain_a",
    "protocol_param":"",
    "obfs":"tls1.2_ticket_auth",
    "obfs_param":"",
    "redirect":"",
    "dns_ipv6":false,
    "fast_open":false,
    "workers":1
}
请问是我的配置问题还是别的原因？

**Comment by zhengwuji** [comment]
像你这种问 问题方式，态度，别人看了会烦的！你应该去看学如何学问题方式！

**Comment by Tanlet** [comment]
兄弟！刚过完年，不用这么大火气吧！
作为提问者，我不应该直接了当地指示现象所在吗？同时，为帮助开发者，提问者不是应该提出问题的可疑点吗？
我的配置为按官方文档来设置的。
https://github.com/shadowsocksr-backup/shadowsocks-rss/blob/master/ssr.md
文档说明，“
协议推荐：协议用auth_chain_*最佳，此时推荐不使用加密（设置为none），混淆随意”
对这些问题，你们应该可能都看怕了。对于我来说，我更想知道是因为配置出现问题，还是ssr已经被档破解了。

**Comment by zhengwuji** [comment]
tls1.2_ticket_auth目前只知道这个有问题！但是具体什么问题不清楚！有一位开发者认为极有可能是针对 SSR 的 TLS 混淆，也就是说SSR的TLS有问题！毕竟SSR这个软件目前知道的没有人去开放研究了！

**Comment by zhengwuji** [comment]
哦！对了顺便补充一下！既然是作为一个提问者，那应该要把问题描述清楚！比如你被墙的主机，SSR的工作日志应该提供上来，因为现在你是向开发者提问，那么应该提供对开发者有帮助分析的文件。作为提问者是不是不应该说  别问我为什么又是“又”。 既然是提问者，那么开发者要问你，你不应该拒绝。毕竟这个软件是免费，不收费的，所以没有这个义务去专门找你问是什么问题！你是用脚本搭建还是手动搭建，用的centos还是ubuntu，是安卓手机还是苹果手机，版本是多少等等问题！所以要先去学怎么提问问题。面向什么样的人该提问什么样的问题！

**Comment by Akkariiin** [comment]
“人的一生当然要靠自我奋斗，当然也要考虑历史的进程”啊~

**Comment by a1101298599** [comment]
别用tls1.2_ticket_auth
