### ISSUE TITLE
根据此论文，是否意味着SS已经能够被探测？

### ISSUE THREAD

**Issue by YanzheL** [shadowsocksrr/shadowsocksr#44]
[The Random Forest Based Detection of Shadowsock's Traffic](http://ieeexplore.ieee.org/document/8048116/?reload=true#full-text-section)

https://github.com/shadowsocks/shadowsocks/issues/988

**Comment by KarlM11** [comment]
没有明确的证据表明这件事。但根据 @breakwa11 之前的研究以及一些其它的消息，我个人倾向于原版协议（非 AEAD 系列）已经不适合使用。
