### ISSUE TITLE
多核利用率问题

### ISSUE THREAD

**Issue by ntgeralt** [shadowsocksrr/shadowsocksr#49]
你好，我在四核的香橙派搭建ssr服务端（-Python），多人跑满宽带时发现cpu利用率不高 ，似乎无法用到四核心。请教一下如何用上多核心。

**Comment by Akkariiin** [comment]
py是单线程的，所以无法充分利用多核优势
多人的话，试试在不同端口上各开服务器进程

**Comment by Aster-the-Med-Stu** [comment]
抱歉 Python 是可以多进程的…只要 import 一个包@Akkariiin

https://docs.python.org/3.4/library/multiprocessing.html?highlight=process

**Comment by Akkariiin** [comment]
@Aster-the-Med-Stu 这是多进程而不是多线程啦
