### ISSUE TITLE
服务启动后，每当有用户链接的时候怎么调试跟踪代码的执行流程？

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [shadowsocksrr/shadowsocksr#54]
阿卡丽同学 服务端成功启动也已经实现了数据库多用户的关联但是我现在不知道怎么调试，
比如服务启动在了800端口 这个时候有一个客户端连接了我的800端口 我该怎么才能跟踪调试链接800端口后的程序执行过程呢？ 
我使用Pycharm可以调试服务端server.py的启动过程， 但是 却追踪不到用户链接时候的代码执行流程 。 我是新手 帮帮我吧

**Comment by KarlM11** [comment]
看 `tcprelay.py`，服务端和客户端都在这里。沿着状态机一路着过去就好了。

**Comment by DreamSeekerKaiser** [comment]
感谢你 @AspirinGeyer
