### ISSUE TITLE
怎么自动分流？

### ISSUE THREAD

**Issue by LoogCP** [shadowsocksrr/shadowsocksr#55]
我有一块派，想在这上面搭建一个dns转发并且安装ssr客户端，让局域网内的设备dns设置为派的ip地址，达到翻墙的目的。
我想知道怎么像pac那样自动分流，根据不同目标主机选择直连还是代理。谢了

**Comment by ghost** [comment]
dnsmasq+[dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)
