### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [shadowsocksrr/shadowsocksr#59]
经常性的出现这个错误 导致网络机器缓缓 这是什么原因呢老板？

shadowsocksr-3.2.1
centos 6.5
主机地址 大陆 
访问网址  优酷看视频~

**Comment by Akkariiin** [comment]
请提供详细的错误日志

**Comment by DreamSeekerKaiser** [comment]
2018-05-24 21:23:25 ERROR    tcprelay.py:1039 [Errno 32] Broken pipe
2018-05-24 21:23:25 ERROR    tcprelay.py:1041 remote error, when connect to vali.cp31.ott.cibntv.net:80
user-config --配置如下

{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "m",
    "method": "aes-128-ctr",
    "protocol": "auth_sha1_v4_compatible",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

"additional_ports" : {
    "800": {
        "passwd": "kaiser",
        "method": "rc4-md5",
        "protocol": "auth_aes128_md5",
        "protocol_param": "#",
        "obfs": "plain",
        "obfs_param": ""
    },
    "231": {
        "passwd": "pass",
        "method": "aes-128-ctr",
        "protocol": "auth_aes128_md5",
        "protocol_param": "#",
        "obfs": "tls1.2_ticket_auth_compatible",
        "obfs_param": ""
    }
},

    "additional_ports_only" : true, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": true
}

**Comment by Akkariiin** [comment]
```
2018-05-24 21:23:25 ERROR tcprelay.py:1039 [Errno 32] Broken pipe
2018-05-24 21:23:25 ERROR tcprelay.py:1041 remote error, when connect to vali.cp31.ott.cibntv.net:80
```
看起来是服务器连接问题
请登陆到服务器上后尝试不通过SSR直接访问vali.cp31.ott.cibntv.net
如果服务器有桌面环境可以试着直接在服务器上播放 优酷视频 来确认问题所在

**Comment by DreamSeekerKaiser** [comment]
谢谢阿卡丽 么么哒
