### ISSUE TITLE
glzjinmod  这个怎么用啊？

### ISSUE THREAD

**Issue by 5UFKEFU** [shadowsocksrr/shadowsocksr#6]
manyuser https://github.com/glzjin/shadowsocks.git  我看很长时间没有更新了，而且我最近发现，我通过mod_mu的方式修改了用户名后，服务端这里没有生效啊。这个怎么弄?不能用户那里修改一下密码，我这里就要重启一下服务端吧？
我看说明文档里是支持 glzjinmod的方式的，但怎么也找不到使用说明。

**Comment by 5UFKEFU** [comment]
补充一下，只是单端口多用户存在问题。

**Comment by Akkariiin** [comment]
不知道
SSRR最近没有对 `manyuser with mysql`、`manyuser with mudbjson`、`manyuser with mu api v2` 提供支持的计划

见 https://github.com/shadowsocksrr/shadowsocks-rss/issues/2#issuecomment-324215192

并且，在glzjin上遇到的问题，可以去glzjin提交issue

_貌似glzjin最近好像没有维护了吧_

**Comment by glzjin** [comment]
是的，没有，回来打个卡了。

**Comment by Akkariiin** [comment]
@glzjin 😂

P:能暂时整一下libev的依赖么
