### ISSUE TITLE
Question:关于协议被检测

### ISSUE THREAD

**Issue by Sak94664** [shadowsocksrr/shadowsocksr#64]
***听说*** 最近tls1.2_ticket_auth被检测出来了，如果只是自己用，会不会被检测出来？或者说还有没有好的替代的混淆呢？

如果说这个issue发在这里不合适，请作者关闭这个issue :)

**Comment by hamjin** [comment]
那好像是ss社区来吓唬的，只要所有用户都是TLS1.2混淆，并且设好转发，一点事都没有(我自己就在用)

**Comment by Sak94664** [comment]
嗯...一个在Texas的服务器，用aes256 tls1.2，跑了500M，给封了。(自用

**Comment by hamjin** [comment]
。。我一个NJ的vultr,一个jp的vultr 都没被封，倒是我删了jp的后那个ip被封了。不过nj的vultr没封，每天下载ubuntu镜像用，也是tls1.2-ticket-auth,有混淆参数及对应网站

**Comment by hamjin** [comment]
实在不行就用V2Ray复活vps(websocket+cdn(+tls)),另外不用tls1.2 ticket-auth就用http simple/post

**Comment by hamjin** [comment]
还是没用就plain＋auth chain b/auth aes128 md5+chacha20-ietf/aes-128-ctr

**Comment by Akkariiin** [comment]
tls1.2设置正确的端口协议和redirect就没事

**Comment by Sak94664** [comment]
@Akkariiin 请问一下redirect是怎么redirect呢？

**Comment by hamjin** [comment]
在user-config.json中有一"redirect": ""的东西
在引号中写上自己的TLS server地址(如127.0.0.1:443或www.baidu.con:443)
没有就重新clone仓库，并进入仓库执行./initcfg.sh

**Comment by hamjin** [comment]
分端口重定向(适用于不同端口上的混淆不同，重定向到不同服务器，*号可加可不加，src: https://doub.io/ss-jc48/ ,原本破娃的blogspot上有，可是她删了。。。)
"redirect":["*:8443#127.0.0.1:443",":698#127.0.0.1:443"],

**Comment by jyf007** [comment]
thanks the redirect is works.
