### ISSUE TITLE
服务用一段时间会挂

### ISSUE THREAD

**Issue by Phantom0day** [shadowsocksrr/shadowsocksr#65]
如题，我几个服务器都出现了这个问题，在用一段时间后服务器的ss就连不上了，登录查看进程已经挂了。
重启服务后，可以继续使用了
![screenshot from 2018-06-26 08-52-41](https://user-images.githubusercontent.com/32887345/41882932-51a4e412-791e-11e8-9d70-4f1fdc787c60.png)
![screenshot from 2018-06-26 08-51-33](https://user-images.githubusercontent.com/32887345/41882934-55f699fc-791e-11e8-9e71-b2dd33d72004.png)

**Comment by DreamSeekerKaiser** [comment]
可以用supervistord  每过1个小时restart一次

**Comment by cjjdaq** [comment]
的确有此问题

**Comment by Phantom0day** [comment]
现在又出现这个问题了
我看了系统日志，应该是因为如下bug
![image](https://user-images.githubusercontent.com/32887345/43173699-dbd4a52e-8fe8-11e8-9320-58da41d65a9b.png)

**Comment by Akkariiin** [comment]
请提供python版本、服务器操作系统版本、以及安装脚本（如果有的话）

**Comment by Phantom0day** [comment]
![image](https://user-images.githubusercontent.com/32887345/47140253-5b448000-d2f0-11e8-81da-4e8a7d9cbc75.png)
抱歉回复较慢，最近比较忙 没怎么关注ss 好像也没有再出问题了
脚本用的https://teddysun.com/486.html

**Comment by Hypdncy** [comment]
> 请提供python版本、服务器操作系统版本、以及安装脚本（如果有的话）

您好，能给我一个新的link or package吗，现在网上流传的都是挂了木马的，我的邮箱hypdncy@163.com

**Comment by import-yuefeng** [comment]
如果有兴趣请使用我搭建的docker版本的shadowsocksR，具体的docker hub链接如下: https://hub.docker.com/r/catone/shadowsocks/tags/
其中catone/shadowsocks:0.0.1为shadowsocks版本
shadowsocksR版本的tag为0.0.2，需要外置虚拟卷来修改混淆协议。

--

On Sunday, Oct 28, 2018 at 00:01, 还原丿丶那场雨 <notifications@github.com<mailto:notifications@github.com>> wrote:

请提供python版本、服务器操作系统版本、以及安装脚本（如果有的话）

您好，能给我一个新的link or package吗，现在网上流传的都是挂了木马的，我的邮箱hypdncy@163.com<mailto:hypdncy@163.com>
