### ISSUE TITLE
阿卡丽同志  这个文章你怎么看？

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [shadowsocksrr/shadowsocksr#68]
https://www.jianshu.com/p/1b3d3b71c32d

**Comment by Justsoos** [comment]
此作者 xcjbd ，特征与无特性本身就是相互制约的，没有绝对。
绝对的，就是白名单，什么 狗屁协议在白名单面前都是一个死字。
为什么他揭露ssr这么容易被发现至今快10个月，现在市面上ssr还有这么多用户，这么大市场？

用脑子想想。不值一驳

**Comment by Justsoos** [comment]
https://www.jianshu.com/u/43f51bce44dd
去看看这作者文章列表，就根本没必要看此文。
整个一个外行，技术小白

**Comment by xqdoo00o** [comment]
感觉还是有点道理的， 我逛的 各种论坛/群里说 被ban IP的网友，用ssr的 跟 用原版ss/v2ray 相比 起码有 9比1，甚至更高。

**Comment by KyonCN** [comment]
我在某敏感时期被ban了三台香港小鸡 后来全部转向v2了 不确定是敏感时期被检测到了还是因为连坐被防火墙拉了ip段 流量很小 只有两三个人看看邮件和油管

**Comment by mizukino** [comment]
ssr特性不就是换密码。。。
auth_chain_b定期换密码就完事了
