### ISSUE TITLE
多IP状态下 只有主IP的UDP转发可用,其他IP都无法转发

### ISSUE THREAD

**Issue by hejiahuan0722** [shadowsocksrr/shadowsocksr#74]
多IP状态下 只有主IP的UDP转发可用,其他IP都无法转发

绑定了240个IP 用sstap测试连接 只有主IP成功转发UDP,其他IP全部无法转发,
TCP所有IP都正常, 入口IP与出口IP相同,

求UDP 多IP转发方法,, 跪求 跪求

**Comment by hejiahuan0722** [comment]
系统:centos7
配置:
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 3008,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "*********",
    "method": "chacha20",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": true

**Comment by ghost** [comment]
linux中，如果在一张网卡上配置多个同一网段的ip，那么除了第一个被配置的之外，其余的都将是secondary IP。如果一个udp服务器bind了0.0.0.0地址，而一个udp客户端来连接一个secondary IP，那么连接是不会正常的，抓包会发现udp服务器的回复包的源ip是一个primary IP，而不是它所连接的secondary IP。对于tcp则不存在这样的问题。这是linux内核协议栈所决定的。

你需要指定IP地址，不要写0.0.0.0

**Comment by Akkariiin** [comment]
@VoganWong 感谢~~~

**Comment by yilin101** [comment]
> 多IP状态下 只有主IP的UDP转发可用,其他IP都无法转发
> 
> 绑定了240个IP 用sstap测试连接 只有主IP成功转发UDP,其他IP全部无法转发,
> TCP所有IP都正常, 入口IP与出口IP相同,
> 
> 求UDP 多IP转发方法,, 跪求 跪求

你好 这个问题解决了吗 遇到同样的问题 求教
