### ISSUE TITLE
阿卡林巨巨，请更新一下dockerfile

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr#8]
akkariiin/master这个分支用旧的dockerfile已经无法部署了。
请更新，最好是像这种，可以在docker run时加参数的方式。
https://github.com/mritd/dockerfile/blob/master/shadowsocks/Dockerfile

**Comment by Akkariiin** [comment]
https://github.com/mritd/dockerfile/blob/master/shadowsocks/Dockerfile#L30

这里指定了项目路径到原版ss-libev

<hr/>

我想这个issue是不是应该提给 [mritd/dockerfile](https://github.com/mritd/dockerfile) ?

或者你能仔细说明你想表达的意思吗？

**Comment by ghost** [comment]
好的，我到那边也提一下需求。

**Comment by ghost** [comment]
FROM alpine

ENV SERVER_ADDR     0.0.0.0
ENV SERVER_PORT     51348
ENV PASSWORD        psw
ENV METHOD          none
ENV PROTOCOL        auth_chain_d
ENV PROTOCOLPARAM   32
ENV OBFS            tls1.2_ticket_auth
ENV TIMEOUT         300
ENV DNS_ADDR        8.8.8.8
ENV DNS_ADDR_2      8.8.4.4


RUN apk update \
    && apk add python \
    libsodium \
    unzip \
    wget \
  && rm -rf /var/cache/apk/*



RUN wget --no-check-certificate https://github.com/shadowsocksrr/shadowsocksr/archive/akkariiin/master.zip -O /tmp/master.zip \
    && unzip -d /tmp /tmp/master.zip \
    && mv /tmp/shadowsocksr-akkariiin-master ~/shadowsocksr \
    && rm -rf /tmp/*


WORKDIR ~/shadowsocksr/shadowsocks


EXPOSE 51348
CMD python ~/shadowsocksr/shadowsocks/server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS -G $PROTOCOLPARAM



用旧dockerfile稍微改了改，亲测可用

**Comment by mritd** [comment]
😂 才看明白... @eric21 那个是原版的镜像，不是  R 版
