### ISSUE TITLE
这个文章如何？SSRR算法能否避免

### ISSUE THREAD

**Issue by Kry4tal** [shadowsocksrr/shadowsocksr#83]
https://patents.google.com/patent/CN109286576A/

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by Akkariiin** [comment]
担心就开混淆就好了
auth_chain会给包追加随机长度填充

而且说实话，这篇专利实用性不高
想要实作这篇专利的话，首先要准确识别出SS/SSR协议，再记录协议所有流经的流量
然后还要事先采集大量可能被访问的网站的特征，特别是像google这类经常变的网站还要频繁更新

满足上面这些要求的使用场景也就只有APT攻击环境了
但是有这类需求的使用者，为什么不给SS/SSR套个Tor呢？（思考
