### ISSUE TITLE
教程里git clone后面的代码是不是填错了，少了个r . Is there some spelling mistakes in your code?

### ISSUE THREAD

**Issue by xiaoxiaohexy** [shadowsocksrr/shadowsocksr#88]
教程里的(code)：
Debian / Ubuntu:
apt-get install git
git clone https://github.com/shadowsocksr/shadowsocksr.git
(git clone https://github.com/shadowsocks**r**/shadowsocksr.git)

是不是应该更正成(should it be change to)：
git clone https://github.com/shadowsocksrr/shadowsocksr.git
(git clone https://github.com/shadowsocks**rr**/shadowsocksr.git)

**Comment by Akkariiin** [comment]
是故意的，你可以开PR上来改了它
