### ISSUE TITLE
使用 none 加密 无法暂停产品 修改密码一样可以上网 SSR裸奔BUG

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocksrr/shadowsocksr#89]
SSR 2.6.12 多用户 Lengedsocsks  MYSQL 数据库 
服务端none origin plain 密码随便写都能上网 怎么办？这个是不是BUG啊？

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/64482595-4b46cf00-d227-11e9-98c3-d96af0f1d9ab.png)

**Comment by Akkariiin** [comment]
none顾名思义不就是没有加密吗？
