### ISSUE TITLE
URL of clients in README are incorrect

### ISSUE THREAD

**Issue by jfthuong** [shadowsocksrr/shadowsocksr#93]
In README file, the URL for clients are incorrect.

They are written in the format: https://github.com/shadowsocksr/shadowsocksr-csharp but should be https://github.com/shadowsocksrr/shadowsocksr-csharp  (i.e. **shadowsocksrr** - with double 'r' - instead of a **shadowsocsr**).

This applies to all clients except iOS and OpenWRT.

**Comment by AureliusPatiens** [comment]
故意的

**Comment by Akkariiin** [comment]
This is intentional
