### ISSUE TITLE
关于 Redirect Attack 的问题

### ISSUE THREAD

**Issue by redapple0204** [shadowsocksrr/shadowsocksr#95]
SS那边已经被曝出使用传统流加密会被Redirect Attack并且获取数据包内容，详情文档如下。（真实性不确保，仅供参考）
[Redirect attack on Shadowsocks stream ciphers (2).pdf](https://github.com/shadowsocksrr/shadowsocksr/files/4192943/Redirect.attack.on.Shadowsocks.stream.ciphers.2.pdf)
目前在插件文档里并没有看到任何协议可以防范Redirect Attack，仅可以防范Replay Attack，不知道SSRR是否有计划添加防范Redirect Attack的协议。
谢谢！

**Comment by Akkariiin** [comment]
Redirect Attack 基于明文位置的可预测性， 且 需要在至少可以完成Replay Attack的前提下进行

破娃加入的大部分ssr协议均可提供对Replay Attack的抵抗
且auth_chain系列协议的随机长度填充特性可以保证无法预测数据存储位置
故此次暴露出的攻击方法对SSR系列无影响
